ALTER TABLE HOTEL DROP CONSTRAINT UNQ_HOTEL_0
ALTER TABLE ROOM DROP CONSTRAINT FK_ROOM_HOTEL_ID
ALTER TABLE ROOM DROP CONSTRAINT UNQ_ROOM_0
ALTER TABLE PC2_PARTS2 DROP CONSTRAINT PC2_PARTS2_pcs_ID
ALTER TABLE PC2_PARTS2 DROP CONSTRAINT PC2_PARTS2parts_ID
DROP TABLE HOTEL
DROP TABLE ROOM
DROP TABLE PC2
DROP TABLE PARTS2
DROP TABLE PC2_PARTS2
