ALTER TABLE HOTEL DROP CONSTRAINT UNQ_HOTEL_0
ALTER TABLE ROOM DROP CONSTRAINT FK_ROOM_HOTEL_ID
ALTER TABLE ROOM DROP CONSTRAINT UNQ_ROOM_0
ALTER TABLE PC_PARTS DROP CONSTRAINT FK_PC_PARTS_pcs_ID
ALTER TABLE PC_PARTS DROP CONSTRAINT PC_PARTS_parts_ID
DROP TABLE HOTEL
DROP TABLE ROOM
DROP TABLE PC
DROP TABLE PARTS
DROP TABLE PC_PARTS
